# Generated by Django 6.0.2 on 2026-02-20 00:29

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0005_api_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooksubscription',
            name='secret',
            field=models.CharField(default=secrets.token_hex, max_length=64),
        ),
    ]
